# Generated by Django 4.0.5 on 2022-06-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmienpiec', '0005_alter_comment_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
