# Generated by Django 4.0.5 on 2022-06-13 07:00

from django.db import migrations, models
import zmienpiec.models


class Migration(migrations.Migration):

    dependencies = [
        ('zmienpiec', '0006_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default='no-image.jpg', null=True, upload_to=zmienpiec.models.path_and_rename),
        ),
    ]
